name: BUILD

on:
  push:
    branches:
      - develop
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint
        run: |
          npm run lint -- --no-fix

      - name: Run type check
        run: |
          npm run type-check

      - name: Run tests
        run: |
          npm run test:unit

      - name: Run circular references check
        run: |
          npm run circular-check

      - name: Build
        run: |
          npm run build

      - name: Upload fluidd.zip
        uses: actions/upload-artifact@v7
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist

  publish-web:
    name: Deploy to Host
    needs: build
    if: ${{ github.repository == 'fluidd-core/fluidd' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download fluidd.zip
        uses: actions/download-artifact@v8
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist

      - name: Prepare Deploy
        run: |
          cp ./server/config.json ./dist/config.json

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}

      - name: Deploy to Host
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: ${{ secrets.DEV_S3_BUCKET_NAME }}
          bucket-region: us-east-1
          dist-id: ${{ secrets.DEV_CF_DISTRIBUTION_ID }}
          delete-removed: true
          no-cache: true
          private: true
